In [1]:
import numpy as np
import pandas as pd

In [2]:
mydata=[234,235,236]

In [3]:
myindex=['usa','canada','france']

In [4]:
myseri=pd.Series(data=mydata)

In [5]:
myseri

0    234
1    235
2    236
dtype: int64

In [6]:
myseriindex=pd.Series(data=myindex)
myseriindex

0       usa
1    canada
2    france
dtype: object

In [7]:
myseri=pd.Series(data=mydata,index=myindex)
myseri

usa       234
canada    235
france    236
dtype: int64

In [8]:
ages={'prasath':21,'arun':23}
ages

{'prasath': 21, 'arun': 23}

In [9]:
pd.Series(ages)

prasath    21
arun       23
dtype: int64

In [10]:
myseri=pd.Series(index=myindex,data=mydata)
myseri

usa       234
canada    235
france    236
dtype: int64

In [12]:
df=pd.DataFrame(np.random.randint(0,100,size=(4,3)),columns=['Column1','Column2','Column3'])
df

Column1  Column2  Column3
0       60       92        0
1       40       46       63
2       60       34       67
3        5       55       87

In [14]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [15]:
ar=np.array([1,2,3])
ar

array([1, 2, 3])

In [20]:
df=pd.DataFrame({'Values':[1,2,3,4]})
df['Values']>3

0    False
1    False
2    False
3     True
Name: Values, dtype: bool

In [21]:
arr=np.array([[1,2,3],[4,5,6]])
arr[:,[0,1]]=arr[:,[1,0]]

In [22]:
arr

array([[2, 1, 3],
       [5, 4, 6]])

In [23]:
arr=np.array([[1,2,3],[4,5,6]])
arr[[0,1]]=arr[[1,0]]

In [24]:
arr


array([[4, 5, 6],
       [1, 2, 3]])

In [26]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
arr=np.array([1,2,3,4,6])
tot=arr.astype(float)
tot

array([1., 2., 3., 4., 6.])

In [29]:
arr=np.array([1,2,2,3,4,5,6,6,7])
np.unique(arr)

array([1, 2, 3, 4, 5, 6, 7])

In [30]:
a1=np.array([1,2,3,6])
a2=np.array([2,2,3,5])
total=a1==a2
total

array([False,  True,  True, False])